system/web.php

Please test to make sure nothing else gets horribly broken.
https://github.com/2pisoftware/cmfive-core/issues/3

Fixed CSRF issues that prevents a new token being generated on page refresh

---

system/modules/task/models/TaskService.php

Assignee of a task should receive emails, previously it was only creator/owners

Added assignee to receiver of task emails

---

.gitignore
system/modules/admin/install/migrations/20160219180955-Adminlookupseeding.php

this fixes the initial admin lookup seed migration which breaks installation (at least for me) and I don't know how this ever worked!

fixing adminlookupseeding migration

---

system/modules/task/task.roles.php

https://crm.2pisoftware.com/task/edit/3952#details
Add endpoints to task_user role

Task [3952]: BUG Task, task_users cannot add task subscribers yet they can see the button.

---

system/modules/task/models/Task.php
system/modules/task/templates/edit.tpl.php
system/tests/selenium/cm5_suite_unassign_task.html
system/tests/selenium/unassign_task.html

Fixes task view for unassigned tasks

Check assigned user and user exists for subscribers

---

system/modules/task/task.hooks.php

added feature: show Taskgroup in Task notification email

added feature: show Taskgroup in Task notification email

---

system/html.php

fixed bug -> $this can not be used in static methods

fixed bug -> $this can not be used in static methods

---

system/web.php

fixed array bug in _getCommandPath function

fixed array bug in _getCommandPath function

---

system/modules/report/actions/addmembers.php
system/modules/report/actions/deletemember.php
system/modules/report/actions/runreport.php
system/modules/report/templates/runreport.tpl.php

- Checks if users are members of reports before allowing the ability to view & run them

Hotfix: Fix running report permissions

---

system/modules/admin/actions/users.php
system/modules/admin/admin.hooks.php
system/modules/auth/auth.hooks.php

Added a hook to the admin module which triggers when the Contact table is updated. This hook checks if a corresponding user is external, & if so, will change their password to match their email.

Feature: update external user login when updating contact

---

system/config.php
system/modules/admin/models/SesTransport.php
system/modules/admin/models/SwiftMailerTransport.php

Required response to blocked Client mail
New Config entires can  force Company to always be sender
refs:
issues: ClientFaultReport

fix: Allow Override on Mail ReplyTo

---

system/modules/report/models/ReportService.php

A minor 'patch' found in a prod install, never committed
Probably to allow for anon. reports execution
refs:
issues: maintain consistent upgrades

fix: Reports patch found hanging in Prod

---

.github/pull_request_template.md

Added a pull request template that can be used on future pull requests.

feat: Added a pull request template

---

system/classes/Config.php

feature is implemented to support future CICD development

feat: capability to update config registry from json

---

system/modules/file/partials/actions/listattachments.php
system/modules/file/partials/templates/listattachments.tpl.php

- Fixed a bug causing different attachment partials to share the same page number stored in the session/request data.
refs: 9261

fix: attachment pages session

---

system/classes/Config.php

This is closing off some unfished issues from this #82 pull request.
- Added comment to method.
- Replaced usage of array() with shorthand [].
- Added parameter type hinting.
- Added return type hinting.

feat: config json

---

.github/semantic.yml
.github/workflows/main.yml
.github/workflows/stale.yml
system/modules/admin/templates/user/edit.tpl.php
system/modules/admin/tests/acceptance/TemplateCest.php
system/modules/auth/templates/layout.tpl.php
system/modules/channels/tests/acceptance/helpers/CmfiveChannelsModule.php
system/templates/vue-components/form/elements/autocomplete.vue.js

Adding a github actions file to run tests on PR to develop
Add .github/workflows/main.yml  file to add support for running tests in Github Actions
Add .github/workflows/stale.yml file to close stale PRs (default 30 days)
Add .github/semantic.yml file to support semantic pull requests app
refs: 9648

feat: add github actions for automated testing

---

.github/semantic.yml
.github/workflows/main.yml
.github/workflows/stale.yml
system/modules/admin/templates/user/edit.tpl.php
system/modules/admin/tests/acceptance/TemplateCest.php
system/modules/auth/templates/layout.tpl.php
system/modules/channels/tests/acceptance/helpers/CmfiveChannelsModule.php
system/modules/timelog/actions/index.php
system/modules/timelog/models/TimelogService.php
system/templates/vue-components/form/elements/autocomplete.vue.js

- Added GitHub Action to run tests.
- Added Github to check for stale pull requests.
- Added Semantic Pull Requests to check that pull request messages are consistent.
- Updates to tests that were failing.
- Updated Timelog pagination to be in days rather than raw Timelog entries.

feat: develop

---

.github/workflows/main.yml
system/modules/admin/tests/acceptance/AdminModuleCest.php
system/modules/admin/tests/acceptance/helpers/CmfiveAdminModule.php
system/modules/channels/tests/acceptance/helpers/CmfiveChannelsModule.php

Hotfix merged into develop instead of master due to pending major release
refs:
issues:

feat: acceptance test improvements

---

system/html.php
system/modules/report/actions/exereport.php
system/modules/report/actions/runreport.php
system/modules/report/templates/runreport.tpl.php
system/modules/report/tests/acceptance/helpers/CmfiveReportModule.php

Replaced deprecated array_key_exists() with isset()

feat: depricated php statement fixed

---

.github/pull_request_template.md
.github/workflows/ci.yml

- Updated CI action for PHP 7.4.
- Updated pull request template.

fix: updated ci action

---

.github/workflows/ci.yml
system/modules/auth/templates/login.tpl.php
system/modules/task/models/TaskService.php

- Added autofocus to the MFA input field of the login page.

fix: mfa focus

---

system/classes/DbPDO.php
system/classes/DbService.php

Fixed a couple of issues that were not as easy to pick up because PHP only issues a notice for them and doesn't throw an exception.
- Added an if check to fetchElment() for when false is returned.
- Added an is_scalar check to getObject() for when the value is an array.
refs: 10223

fix: db issues

---

system/web.php

Currently when a database connection fails nothing is logged so it can be difficult to debug issues that aren't common.
- Added a log message for when a database connection cannot be made.

fix: better logging

---

system/classes/DbService.php
system/modules/admin/actions/get_countries.php
system/modules/admin/install/migrations/20210707125430-AdminAddCountryTable.php
system/modules/admin/install/migrations/seeds/LookupSeeding.php
system/modules/admin/models/AdminService.php
system/modules/admin/models/Country.php
system/modules/auth/models/Contact.php
system/modules/auth/models/User.php

- Added get_countries action.
- Added Country model.
- Added country table migration.
- Added typing to methods.
- Replaced deprecated method usage.
- Added deprecation comments.
- General Commenting.
- Formatting.
- Removed commented code.

feat: added country support

---

system/modules/admin/actions/deletelookup.php
system/modules/admin/actions/get_countries.php
system/modules/admin/actions/users.php
system/modules/admin/install/migrations/20210708103952-AdminRenameCountryColumns.php
system/modules/admin/install/migrations/20210712114520-AdminAddLanguageTable.php
system/modules/admin/models/AdminService.php
system/modules/admin/models/Country.php
system/modules/admin/models/CountryLanguage.php
system/modules/admin/models/Language.php
system/modules/auth/models/User.php
system/web.php

- Added empty check to list users action.
- Added migration.
- Added AdminService methods.
- Renamed properties in Country class.
- Added recursive class auto loading support in the models directory.

feat: country service methods

---

system/modules/admin/models/LookupService.php
system/modules/auth/models/AuthService.php
system/modules/auth/models/User.php
system/modules/auth/partials/actions/removeUser.php
system/modules/task/models/Task.php
system/web.php

- Added comments to methods.
- Replaced usage of deprecated methods.
- Fixed several typos.
- Formatted files.
- Removed commented code.

fix: get object class capitalisation

---

system/modules/file/models/FileService.php

Repetitious code block for file module s3 config refactored
Conforms to (a) 7.4/head dev_prod logic ,
and (b) 7.2->7.4 promotion of s3 presigning feature
refs:
issues:
- [ Y ] I'm using the correct PHP Version (7.4 for current, 7.2 for legacy).
- [na] I've added comments to any new methods I've created or where else relevant.
- [na] I've replaced magic method usage on DbService classes with the getInstance() static method.
- [na] I've written any documentation for new features or where else relevant in the docs [repo](https://github.com/2pisoftware/cmfive-docs).
new function on file service: getS3ClientBelowFilesystem()
Repetitious code block for file module s3 config refactored
Conforms to (a) 7.4/head dev_prod logic ,
and (b) 7.2->7.4 promotion of s3 presigning feature
refs:
issues: …

fix: Correct s3 refactor conforming legacy vs head

---

.github/workflows/ci.yml
system/modules/channels/config.php
system/modules/channels/models/EmailChannelOption.php
system/modules/channels/tests/acceptance/ChannelsModuleCest.php
system/modules/channels/tests/acceptance/helpers/CmfiveChannelsModule.php
system/modules/main/tests/unit/RequestTest.php

fix: fix broken unit tests

---

system/modules/insights/actions/export/bindpdf.php
system/modules/insights/actions/export/pdf.php
system/modules/insights/actions/runInsight.php
system/modules/insights/models/InsightService.php
system/modules/insights/templates/export/bindpdf.tpl.php
system/modules/insights/templates/runInsight.tpl.php
system/templates/layout.tpl.php

Fixing issue with export to PDF option for insights
- Changed Vanilla JavaScript to jQuery where foundation function is used
- Removed duplicate of select option in drop-down for template select
refs: 10151

feat: Insights JavaScript Fix

---

.github/workflows/ci.yml
system/modules/admin/actions/useradd.php
system/modules/admin/tests/acceptance/helpers/CmfiveAdminModule.php

Backwards breaking changes marked with a ```!``` in changelog, if unsure that it _may_ be a backwards breaking change it will still be marked as such.
Adds support for PHP 8.1 and MySQL 8, removes deprecated functions marked for removal
- *!* Removed magic __get functions from Web, DbObject and DbService
- *!* Removed ```request()``` from Web in lieu of the Request static class
- *!* Also removed ```cmp_weights()```, ```sendFile()```, ```service()```, ```_callPreListeners()``` and ```_callPostListeners()``` from Web
- Commented out CachedTemplate in Web, expected to be removed in future version
- Added support for code sniffing in Github actions over multiple PHP versions
- Migrated all usages of magic ```$w::__get``` method to the proper ```DbService::getInstance($w)``` function
- *!* …

feat!: add support for PHP8.1

---

system/classes/html/form/Select.php
system/modules/admin/models/AuditService.php
system/modules/channels/models/ChannelService.php
system/modules/file/models/Attachment.php
system/modules/form/models/ExternalFormXMLProcessor.php
system/modules/form/models/FormApplication.php
system/modules/task/models/TaskService.php

- [Y ] I'm using the correct PHP Version (8.1).
- [Y ] I've replaced magic method usage on DbService classes with the getInstance() static method.
Various Spot Patches from 8.1 testing
system/classes/html/form/Select.php : null cast Options
system/modules/admin/models/AuditService.php : date casts in range
system/modules/channels/models/ChannelService.php : $this->w->db
system/modules/file/models/Attachment.php : null cast on Path
system/modules/form/models/ExternalFormXMLProcessor.php : correct GetInstance typo
system/modules/form/models/FormApplication.php : $this->w->db
system/modules/task/models/TaskService.php : undo quote escape failure
refs:
issues:

Various Spot Patches

---

system/functions.php
system/html.php
system/modules/admin/actions/ajaxAddComment.php
system/modules/admin/actions/deleteprintfile.php
system/modules/admin/actions/users.php
system/modules/admin/install/migrations/20210707125430-AdminAddCountryTable.php
system/modules/admin/install/migrations/20210712114520-AdminAddLanguageTable.php
system/modules/admin/models/AwsTransport.php
system/modules/admin/models/CommentService.php
system/modules/admin/models/SesTransport.php
system/modules/admin/models/SwiftMailerTransport.php
system/modules/auth/models/AuthService.php
system/modules/channels/models/EmailChannelOption.php
system/modules/file/actions/admin/moveToAdapter.php
system/modules/file/actions/attachment/delete.php
system/modules/file/actions/attachment/restore.php
system/modules/file/actions/edit.php
system/modules/file/actions/new.php
system/modules/file/models/FilePolyfill.php
system/modules/file/partials/templates/attachment_item.tpl.php
system/modules/report/models/Report.php
system/modules/report/models/ReportService.php
system/modules/task/models/Task.php
system/modules/task/models/TicketEmailProcessor.php
system/modules/task/task.actions.php
system/web.php

- [Y ] I'm using the correct PHP Version (8.1)!
- [? ] I've added comments to any new methods I've created or where else relevant.
- [Y ] I've replaced magic method usage on DbService classes with the getInstance() static method.
- [? ] I've written any documentation for new features or where else relevant in the docs [repo](https://github.com/2pisoftware/cmfive-docs).
Various spot patches revealed during large scale module migration.

Fix: Patching From Module Observations

---

.github/workflows/ci.yml
README.md
system/classes/DbObject.php
system/modules/admin/tests/acceptance/helpers/CmfiveAdminModule.php
system/modules/channels/tests/acceptance/helpers/CmfiveChannelsModule.php
system/modules/form/tests/acceptance/helpers/CmfiveFormModule.php
system/modules/inbox/tests/acceptance/helpers/CmfiveInboxModule.php
system/modules/main/tests/acceptance/helpers/CmfiveConfig.php
system/modules/report/tests/acceptance/helpers/CmfiveReportModule.php
system/modules/tag/tests/acceptance/helpers/CmfiveTagModule.php
system/modules/task/tests/acceptance/helpers/CmfiveTaskModule.php
system/modules/timelog/tests/acceptance/helpers/CmfiveTimelogModule.php

Promote codecpt5 into dev to allow ci test run against upgraded boilerplate

Feature: work to codeception5

---

.github/workflows/ci.yml
README.md
system/classes/DbObject.php
system/modules/admin/tests/acceptance/helpers/CmfiveAdminModule.php
system/modules/channels/tests/acceptance/helpers/CmfiveChannelsModule.php
system/modules/form/tests/acceptance/helpers/CmfiveFormModule.php
system/modules/inbox/tests/acceptance/helpers/CmfiveInboxModule.php
system/modules/main/tests/acceptance/helpers/CmfiveConfig.php
system/modules/report/tests/acceptance/helpers/CmfiveReportModule.php
system/modules/tag/tests/acceptance/helpers/CmfiveTagModule.php
system/modules/task/tests/acceptance/helpers/CmfiveTaskModule.php
system/modules/timelog/actions/move.php
system/modules/timelog/partials/templates/listtimelog.tpl.php
system/modules/timelog/templates/index.tpl.php
system/modules/timelog/templates/move.tpl.php
system/modules/timelog/tests/acceptance/helpers/CmfiveTimelogModule.php

Promote codecept5 into MASTER to allow ci test run against upgraded boilerplate

feature: raise master to codeception5

---

system/modules/form/partials/templates/listform.tpl.php
system/templates/layout-foundation.tpl.php

Bind modal for table buttons of mapped form displays
Expose binding with script function in Foundation template
Patch form vue.js to rebind buttons after table row updates

Fix: bind modal for table buttons of mapped form displays

---

system/modules/report/actions/edit.php

Fix edit.php unhandled null

---

.github/workflows/ci.yml

Add Node 20 and create a matrix for node testing.
Add PHP 8.3 and create a matrix for phpCS
Added node 20 + matrix
Added php 8.3 + matrix
refs:
issues:

Add node matrix

---

.github/workflows/ci.yml

Add CI changes for Master as per #254 
refs:
issues:

chore(ci): CI changes for master

---

system/modules/timelog/actions/edit.php
system/modules/timelog/tests/acceptance/playwright/timelog.utils.ts

…log it out in Develop branch
refs:
issues:

dedupe testing in develop CI/CD run

---

.github/workflows/ci.yml
system/classes/HtmlBootstrap5.php
system/classes/components/CmfiveComponentRegister.php
system/classes/components/CmfiveStyleComponent.php
system/modules/admin/actions/groups.php
system/modules/admin/actions/moreInfo.php
system/modules/admin/actions/templates/edit.php
system/modules/admin/actions/user/edit.php
system/modules/admin/actions/useradd.php
system/modules/admin/actions/users.php
system/modules/admin/templates/users.tpl.php
system/modules/auth/models/User.php
system/modules/insights/actions/index.php
system/templates/base/src/js/app.ts
system/templates/base/src/scss/app.scss

Fix merge conflicts - lots of duplicated code
- Fix merge conflict issues
refs: #320 
issues:

fix: fixing merge conflicts from master merge

---

system/classes/components/CmfiveStyleComponent.php
system/modules/timelog/actions/edit.php

fix: removed duplications and debug code

---

.github/workflows/ci.yml

We're switching from master to main, this corrects the action pr branch targets
refs:
issues:

fix: correct pr target branch

---

.github/workflows/ci.yml

Dynamic boilerplate branch/image

---

.github/workflows/ci.yml

Update to new env var

---

.github/workflows/ci.yml

Feat: Fallback for ref

---

.github/workflows/ci.yml

Feat: Change fallback

---

.github/workflows/ci.yml

Remove push rule for develop

---

.github/workflows/ci.yml
system/modules/timelog/tests/acceptance/playwright/timelog.test.ts
system/modules/timelog/tests/acceptance/playwright/timelog.utils.ts
system/web.php

OMG I think we've fixed the timezone thing!!! Plus updated timelog tests to verify that the correct date and times are displayed.
refs:
issues:

Fix/timezone fix 
